ARG BASE_IMAGE=harbor.sourcefind.cn:5443/dcu/admin/base/custom:vllm015-ubuntu22.04-dtk26.04-0409-modelzoo:5e4e1ced6f9d
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy
ARG https_proxy
ARG no_proxy

ARG APT_MIRROR
RUN if [ -n "$APT_MIRROR" ]; then \
        sed -i "s|http://[^/]*/ubuntu|${APT_MIRROR}|g" /etc/apt/sources.list; \
    fi && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        cmake \
        ninja-build \
        curl \
        tar \
        build-essential \
        pkg-config \
        python3-dev \
        ca-certificates \
        libboost-dev \
        libboost-stacktrace-dev \
        libffi-dev \
        libssl-dev \
    && rm -rf /var/lib/apt/lists/*

ARG PIP_INDEX_URL
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
        transformers \
        pyyaml \
        uvicorn \
        janus \
        fastapi \
        openai \
        pybind11 \
        xxhash \
        ml_dtypes \
        datasets

ENV XMAKE_ROOT=y
RUN curl -fsSL https://xmake.io/shget.text | bash
ENV PATH="/root/.local/bin:/root/.xmake/bin:${PATH}"

ENV INFINI_ROOT="/root/.infini"
ENV LD_LIBRARY_PATH="$INFINI_ROOT/lib:$LD_LIBRARY_PATH"
ENV LD_LIBRARY_PATH=$(python -c 'import torch, os; print(os.path.join(os.path.dirname(torch.__file__), "lib"))'):$LD_LIBRARY_PATH
ENV PYTHONPATH="/root/.infini/lib:$PYTHONPATH"

WORKDIR /workspace/InfiniLM

RUN xmake repo -u

COPY . ./

RUN xmake build -y _infinilm && xmake install _infinilm && INFINILM_ENABLE_HYGON=1 pip install -e . --no-build-isolation

WORKDIR /workspace
