ARG BASE_IMAGE=cambricon/pytorch:v1.25.3-torch2.1-anolisos8.8-py310
FROM ${BASE_IMAGE}

ENV PATH="/usr/local/python3.10/bin:${PATH}"

RUN ln -sf python3.10 /usr/local/python3.10/bin/python3 && \
    ln -sf python3.10 /usr/local/python3.10/bin/python

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy
ARG https_proxy
ARG no_proxy

RUN dnf install -y dnf-plugins-core && \
    (dnf config-manager --set-enabled powertools || dnf config-manager --set-enabled crb || true) && \
    dnf install -y \
        git \
        cmake \
        ninja-build \
        curl \
        tar \
        gcc \
        gcc-c++ \
        make \
        pkgconf-pkg-config \
        ca-certificates \
        boost-devel \
        libffi-devel \
        openssl-devel \
    && dnf clean all

ARG PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip config set global.index-url "${PIP_INDEX_URL}" && \
    pip install --no-cache-dir --upgrade pip setuptools wheel -i "${PIP_INDEX_URL}" && \
    pip install --no-cache-dir -i "${PIP_INDEX_URL}" \
        transformers \
        pyyaml \
        uvicorn \
        janus \
        fastapi \
        openai \
        pybind11 \
        xxhash \
        ml_dtypes \
        datasets

ENV XMAKE_ROOT=y
RUN curl -fsSL https://xmake.io/shget.text | bash
ENV PATH="/root/.local/bin:/root/.xmake/bin:${PATH}"

ENV INFINI_ROOT="/root/.infini"
ENV LD_LIBRARY_PATH="$INFINI_ROOT/lib:$LD_LIBRARY_PATH"
ENV PYTHONPATH="/root/.infini/lib:$PYTHONPATH"

WORKDIR /workspace

ARG InfiniCore_BRANCH
RUN git clone --recursive https://github.com/Vincent777/InfiniCore.git

WORKDIR /workspace/InfiniCore

RUN git fetch origin ${InfiniCore_BRANCH} && git checkout ${InfiniCore_BRANCH}

RUN xmake repo -u

RUN xmake f -y --cambricon-mlu=y --ccl=y -cv
RUN xmake build -y && xmake install && xmake build -y _infinicore && xmake install _infinicore && pip install -e . -i "${PIP_INDEX_URL}"

WORKDIR /workspace/InfiniLM

COPY . ./

RUN xmake build -y _infinilm && xmake install _infinilm && pip install -e . -i "${PIP_INDEX_URL}"

WORKDIR /workspace
