ARG BASE_IMAGE=sh-harbor.mthreads.com/mcctest/vllm_musa:20251112_hygon
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy
ARG https_proxy
ARG no_proxy

ARG APT_MIRROR
RUN if [ -n "$APT_MIRROR" ]; then \
        sed -i "s|http://[^/]*/ubuntu|${APT_MIRROR}|g" /etc/apt/sources.list; \
    fi && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        cmake \
        ninja-build \
        curl \
        tar \
        build-essential \
        pkg-config \
        python3-dev \
        ca-certificates \
        libboost-all-dev \
        libffi-dev \
        libssl-dev \
    && rm -rf /var/lib/apt/lists/*

ARG PIP_INDEX_URL
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
        transformers \
        pyyaml \
        uvicorn \
        janus \
        fastapi \
        openai \
        pybind11

ENV XMAKE_ROOT=y
RUN curl -fsSL https://xmake.io/shget.text | bash
ENV PATH="/root/.local/bin:/root/.xmake/bin:${PATH}"

ENV INFINI_ROOT="/root/.infinici"
ENV LD_LIBRARY_PATH="$INFINI_ROOT/lib:$LD_LIBRARY_PATH"
ENV PYTHONPATH="/root/.infinici/lib:$PYTHONPATH"

WORKDIR /workspace

ARG InfiniCore_BRANCH
RUN git clone --recursive https://github.com/Vincent777/InfiniCore.git

WORKDIR /workspace/InfiniCore

RUN git fetch origin ${InfiniCore_BRANCH} && git checkout ${InfiniCore_BRANCH}

RUN xmake repo -u

RUN xmake f -y --moore-gpu=y --ccl=y --graph=y -cv
RUN xmake build -y && xmake install && xmake build -y _infinicore && xmake install _infinicore && pip install -e .

WORKDIR /workspace/InfiniLM

COPY . ./

RUN xmake build -y _infinilm && xmake install _infinilm && pip install -e .

WORKDIR /workspace
